name: video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/japantradingcardcenter/flutter-video-player-android/tree/jtcc/video-player-android-2.9.6/packages/video_player/video_player_android
publish_to: none
version: 2.9.6+jtcc.1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.6.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^26.1.5

topics:
  - video
  - video-player
